# Open API Spec documentation: https://swagger.io/docs/specification/about/
openapi: "3.0.0"
info:
  title: Event Store
  version: 1.0.0
paths:
  /events/{eventType}:
    post:
      summary: Save a New Event
      description: |
        Saves a new event of a specific type into the event store.
      parameters:
        - name: eventType
          description: type of an event
          in: path
          required: true
          schema:
            type: string
          example: "cart-item-added"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  eventId: 
                    type: string
                  eventType:
                    type: string
                  data:
                    type: object 
              # examples syntax: https://swagger.io/docs/specification/2-0/adding-examples/                    
              example:
                - eventId: 6a05e510-12ee-47b1-a7a7-2e4259d24809
                  data: {
                    "userId": "0a41c6e5-5ad9-4412-ac5c-fc4cc13e2d6c",
                    "cartId": "a40ea1f4-b2f0-4904-9a3c-85c27efeca92",
                    "productId": "5ca94d88036709a43a429a2b",
                    "numItems": 9,
                    "price": 99.23,
                    "productOptions": {
                      "color": "blue"
                    }
                  }                    
                - eventId: 12106650-4e49-47bd-b93a-0b59a7217497
                  data: {
                    "userId": "5c564d55-5393-48d4-94f5-0ed3402f2a08",
                    "cartId": "ed3ffd05-11cd-41c8-ab58-69292f9a0a9f",
                    "productId": "5ca94e34f7e55570ecb918af",
                    "numItems": 2,
                    "price": 93.82,
                    "productOptions": {
                      "color": "red"
                    }
                  }
              # Example generator:
              # https://www.json-generator.com/
              # [
              #   '{{repeat(1, 3)}}',
              #   {
              #     userId: "{{guid()}}",
              #     cartId: "{{guid()}}",
              #     productId: "{{objectId()}}",
              #     numItems: "{{integer(1, 10)}}",
              #     price: "{{floating(10, 100, 2)}}",
              #     productOptions: {
              #       color: "white"
              #     }
              #   }
              # ]


      responses:
        '200':
          description: |
            Returns success status and IDs of the events that were successfully
            saved.
          content:
            application/json:
              schema:
                type: object
                properties:
                  eventIds:
                    type: array
                    items:
                      type: string
                    example: 
                      - "6a05e510-12ee-47b1-a7a7-2e4259d24809"
                      - "12106650-4e49-47bd-b93a-0b59a7217497"
        '500': 
          description: |
            Returns detailed error explanation in case event store was unable
            to fulfil the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
        '400':
          description: |
            Returns detailed error explanation in case client submitted invalid
            data to the event store
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'


components:
  schemas:
    ErrorObject:
      type: object
      properties:
        errorId:
          type: integer
        description:
          type: string
        details:
          type: string
      example:
        errorId: 2345
        description: "Could not connect to database"
        details: "Please contact sysadmin"
